const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let paused=reduced;
const videos=[...document.querySelectorAll('video')];
const toggle=document.getElementById('motion-toggle');
function syncMotion(){document.body.classList.toggle('motion-paused',paused);videos.forEach(v=>{if(paused)v.pause();else if(v.dataset.visible==='true'&&v.dataset.userPaused!=='true')v.play().catch(()=>{});});}
syncMotion();
if(!reduced)document.body.classList.add('js-motion');
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target);}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(e=>reveal.observe(e));
const videoObserver=new IntersectionObserver(entries=>entries.forEach(e=>{e.target.dataset.visible=String(e.isIntersecting);if(e.isIntersecting&&!paused&&e.target.dataset.userPaused!=='true')e.target.play().catch(()=>{});else e.target.pause();}),{threshold:.15});videos.forEach(v=>{v.muted=true;videoObserver.observe(v);v.addEventListener('play',()=>{const b=v.closest('.video-shell').querySelector('.video-pause');b.textContent='Ⅱ';b.setAttribute('aria-label','暂停动态片段');});v.addEventListener('pause',()=>{const b=v.closest('.video-shell').querySelector('.video-pause');b.textContent='▶';b.setAttribute('aria-label','继续动态片段');});});
document.querySelectorAll('.video-pause').forEach(b=>b.addEventListener('click',()=>{const v=b.closest('.video-shell').querySelector('video');if(v.paused){v.dataset.userPaused='false';v.play().catch(()=>{});}else{v.dataset.userPaused='true';v.pause();}}));
document.addEventListener('visibilitychange',()=>{if(document.hidden)videos.forEach(v=>v.pause());else syncMotion();});
const modules={overview:['overview','CAMPUS OVERVIEW','视角变化，数据位置稳定。','移动视角查看厂房，两侧数据保持固定，方便持续阅读。'],twin:['detail','DIGITAL TWIN','进入车间，查看设备。','从列表选择产线，视角进入车间，再点击设备查看详情。'],energy:['overview','ENERGY MANAGEMENT','查看能源使用情况。','保留园区场景，集中展示用能与变化，切换后仍能确认位置。'],production:['production','PRODUCTION INSIGHT','查看各地项目进度。','地图定位项目，周边查看产量、计划、库存与质量，下方对比进度。'],business:['business','BUSINESS COCKPIT','集中查看经营情况。','市场、生产与财务分区展示，重点数值突出，图表补充变化。']};
const moduleVideo=document.getElementById('module-video');
function selectModule(button){const key=button.dataset.video,m=modules[key];document.querySelectorAll('[data-video]').forEach(b=>{b.setAttribute('aria-selected',String(b===button));b.tabIndex=b===button?0:-1;});document.getElementById('motion-panel').setAttribute('aria-labelledby',button.id);moduleVideo.pause();moduleVideo.poster=`assets/${m[0]}.webp`;moduleVideo.src=`assets/${key}.mp4`;moduleVideo.dataset.userPaused='false';moduleVideo.load();if(!paused&&moduleVideo.dataset.visible==='true')moduleVideo.play().catch(()=>{});document.getElementById('motion-en').textContent=m[1];document.getElementById('motion-title').textContent=m[2];document.getElementById('motion-copy').textContent=m[3];}
const tabs=[...document.querySelectorAll('[data-video]')];tabs.forEach((b,i)=>{b.tabIndex=i===0?0:-1;b.addEventListener('click',()=>selectModule(b));b.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();let next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();selectModule(tabs[next]);}});});
document.querySelectorAll('[data-layout]').forEach(b=>b.addEventListener('click',()=>{const data=b.dataset.layout==='data';document.querySelectorAll('[data-layout]').forEach(e=>{e.classList.toggle('active',e===b);e.setAttribute('aria-pressed',String(e===b));});document.getElementById('layout-demo').classList.toggle('data-mode',data);document.getElementById('demo-title').textContent=data?'重点数据与变化':'园区全景';document.getElementById('demo-sub').textContent=data?'重点数据居中，其他信息分区展示':'保留完整场景与查看空间';document.getElementById('layout-note').textContent=data?'中间展示重点数据，两侧补充统计与异常，先看整体，再看详情。':'中间展示园区，两侧分别查看基本信息与运行状态。';}));
const dialog=document.getElementById('image-dialog');document.querySelectorAll('.zoom-image').forEach(b=>b.addEventListener('click',()=>{dialog.querySelector('img').src=b.dataset.src;dialog.querySelector('img').alt=b.querySelector('img').alt;dialog.showModal();document.body.style.overflow='hidden';}));dialog.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('close',()=>document.body.style.overflow='');
let ticking=false;const progress=document.querySelector('.progress');function scrollProgress(){progress.style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%';ticking=false;}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(scrollProgress);ticking=true;}},{passive:true});scrollProgress();
const hero=document.querySelector('.hero'),scene=document.querySelector('.hero-scene');hero.addEventListener('pointermove',e=>{if(paused||innerWidth<800)return;const x=(e.clientX/innerWidth-.5)*12,y=(e.clientY/innerHeight-.5)*8;scene.style.animation='none';scene.style.transform=`scale(1.08) translate(${x}px,${y}px)`;scene.style.transition='transform 1.2s ease-out';});hero.addEventListener('pointerleave',()=>{scene.style.transform='scale(1.08)';});
