function ensureVideo(v){if(v.dataset.src&&!v.getAttribute('src')){v.src=v.dataset.src;v.load();}v.playbackRate=1.3;}
document.querySelectorAll('video').forEach(v=>{v.defaultPlaybackRate=1.3;v.playbackRate=1.3;v.addEventListener('loadedmetadata',()=>{v.playbackRate=1.3;});});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let paused=reduced;
const videos=[...document.querySelectorAll('.film video')],motionButton=document.querySelector('#motion-toggle');
if(!reduced)document.body.classList.add('motion-on');
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');reveal.unobserve(e.target);}}),{threshold:.04});document.querySelectorAll('.reveal').forEach(e=>reveal.observe(e));
function syncMotion(){document.body.classList.toggle('paused',paused);if(motionButton){motionButton.setAttribute('aria-pressed',String(paused));motionButton.textContent=paused?'开启页面动效 ▶':'暂停页面动效 Ⅱ';}videos.forEach(v=>{if(paused||document.hidden)v.pause();else if(v.dataset.visible==='true'&&v.dataset.userPaused!=='true')v.play().catch(()=>{});});}
videos.forEach(v=>{v.muted=true;v.pause();const b=v.closest('.film').querySelector('.pause');v.addEventListener('play',()=>{b.textContent='Ⅱ';b.setAttribute('aria-label','暂停动态片段');});v.addEventListener('pause',()=>{b.textContent='▶';b.setAttribute('aria-label','继续动态片段');});b.addEventListener('click',()=>{v.dataset.userPaused=String(!v.paused);v.paused?v.play().catch(()=>{}):v.pause();});});
const videoObserver=new IntersectionObserver(es=>es.forEach(e=>{e.target.dataset.visible=String(e.isIntersecting);if(e.isIntersecting&&!paused&&!document.hidden&&e.target.dataset.userPaused!=='true'){ensureVideo(e.target);e.target.play().catch(()=>{});}else e.target.pause();}),{threshold:.15});videos.forEach(v=>videoObserver.observe(v));syncMotion();motionButton?.addEventListener('click',()=>{paused=!paused;syncMotion();});document.addEventListener('visibilitychange',()=>{if(document.hidden)videos.forEach(v=>v.pause());else syncMotion();});
const layerNotes={base:'底图展示区域与通道，为设备提供位置参照。',objects:'设备按统一比例放置，用外形区分不同用途。',all:'数据贴近对应设备，文字保持水平，便于阅读。'};
document.querySelectorAll('[data-layer]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-layer]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});document.querySelector('.layer-demo').dataset.mode=b.dataset.layer;document.querySelector('#layer-note').textContent=layerNotes[b.dataset.layer];}));
const states={running:['●','运行','轻微动效表示设备正在工作。'],idle:['Ⅱ','待机','明确标示等待任务，区别于停机与故障。'],fault:['!','故障','用警示色和文字指出故障设备。'],stopped:['■','停机','弱化停机设备，保留状态名称。']};
document.querySelectorAll('.state-controls [data-state]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.state-controls [data-state]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});const state=b.dataset.state,info=states[state];document.querySelector('.state-preview').dataset.state=state;document.querySelector('.status-tag i').textContent=info[0];document.querySelector('.status-tag strong').textContent=info[1];document.querySelector('#state-note').textContent=info[2];}));
const filmInfo={flexible:['信息更新，位置稳定。','标签在设备旁更新，固定布局方便持续跟踪生产情况。','柔性制造运行片段'],spray:['查看状态、产量与能耗。','设备位置固定，状态与数据持续更新，方便查看生产情况。','喷涂中心运行片段'],yard:['定位成品，查看库存变化。','位置标注展示存放情况，下方图表查看库存与出入库变化。','成品堆场运行片段']};
const tabs=[...document.querySelectorAll('[data-film]')],mainVideo=document.querySelector('#film-panel video');
function selectFilm(b){const k=b.dataset.film,info=filmInfo[k];tabs.forEach(x=>{x.setAttribute('aria-selected',String(x===b));x.tabIndex=x===b?0:-1;});document.querySelector('#film-panel').setAttribute('aria-labelledby',b.id);mainVideo.pause();mainVideo.poster=`assets/${k}-poster.webp`;mainVideo.removeAttribute('src');mainVideo.dataset.src=`assets/${k}.mp4`;if(mainVideo.dataset.visible==='true')ensureVideo(mainVideo);mainVideo.setAttribute('aria-label',info[2]);mainVideo.dataset.userPaused='false';mainVideo.load();if(!paused&&mainVideo.dataset.visible==='true')mainVideo.play().catch(()=>{});document.querySelector('#film-title').textContent=info[0];document.querySelector('#film-text').textContent=info[1];document.querySelector('#film-panel .film-meta>span').innerHTML='<i></i>'+info[2]+' · 静音循环';}
tabs.forEach((b,i)=>{b.tabIndex=i===0?0:-1;b.addEventListener('click',()=>selectFilm(b));b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[n].focus();selectFilm(tabs[n]);}});});
const box=document.querySelector('#lightbox'),large=box.querySelector('img');let zoom=100;function setZoom(n){zoom=Math.max(100,Math.min(250,n));large.style.width=zoom+'%';document.querySelector('#zoom-label').textContent=zoom+'%';document.querySelector('#zoom-out').disabled=zoom===100;document.querySelector('#zoom-in').disabled=zoom===250;}
document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>{large.src=b.dataset.image;large.alt=b.querySelector('img').alt;document.querySelector('#image-caption').textContent=large.alt;setZoom(100);box.showModal();document.body.style.overflow='hidden';}));document.querySelector('#zoom-in').addEventListener('click',()=>setZoom(zoom+25));document.querySelector('#zoom-out').addEventListener('click',()=>setZoom(zoom-25));document.querySelector('#close-image').addEventListener('click',()=>box.close());box.addEventListener('click',e=>{if(e.target===box)box.close();});box.addEventListener('close',()=>document.body.style.overflow='');
let frame=false;addEventListener('scroll',()=>{if(!frame){requestAnimationFrame(()=>{document.querySelector('.read-progress').style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%';frame=false;});frame=true;}},{passive:true});
const hero=document.querySelector('.hero'),art=document.querySelector('.hero-collection');hero.addEventListener('pointermove',e=>{if(paused||innerWidth<900||!art)return;art.style.setProperty('--pointer-x',`${(e.clientX/innerWidth-.5)*36}px`);art.style.setProperty('--pointer-y',`${(e.clientY/innerHeight-.5)*26}px`);art.style.setProperty('--tilt-y',`${(e.clientX/innerWidth-.5)*10}deg`);art.style.setProperty('--tilt-x',`${-(e.clientY/innerHeight-.5)*8}deg`);});hero.addEventListener('pointerleave',()=>{art?.style.setProperty('--pointer-x','0px');art?.style.setProperty('--pointer-y','0px');art?.style.setProperty('--tilt-y','0deg');art?.style.setProperty('--tilt-x','0deg');});
const heroLive=document.querySelector('.hero-live');if(heroLive){heroLive.muted=true;const heroVideoObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!reduced&&!document.hidden){ensureVideo(heroLive);heroLive.play().catch(()=>{});}else heroLive.pause();}),{threshold:.15});heroVideoObserver.observe(heroLive);document.addEventListener('visibilitychange',()=>{if(document.hidden)heroLive.pause();else if(hero.getBoundingClientRect().bottom>0&&!reduced)heroLive.play().catch(()=>{});});}

