(() => {
'use strict';
const names={ready:'确认充电',connecting:'连接检查',charging:'正在充电',confirm:'正在充电',stopping:'正在结束',complete:'充电完成',payment:'支付订单',paying:'支付订单',paid:'支付成功',failed:'连接未成功',receipt:'充电账单',paymentfailed:'支付未完成'};
const copy={ready:['BEFORE YOU START','开始前，把信息交代清楚。','枪号、费用与目标电量集中确认，主按钮始终落在同一位置。'],connecting:['CONNECTING','用连续反馈，接住等待。','连接、设备检查与安全校验分步显示。等待有进度，也可以取消。'],charging:['LIVE FEEDBACK','正在发生的事，看得见。','进度环缓慢流动，电量、费用和时间同步呈现。让动效说明状态，而不是打断阅读。'],confirm:['CONFIRM BEFORE STOP','重要操作，多一步确认。','当前电量与预计费用留在眼前，确认结束和继续充电同时可选。'],stopping:['ENDING SAFELY','先确认结束，再引导拔枪。','结束指令处理期间保持明确提示，避免把点击停止误认为已经断电。'],complete:['SESSION COMPLETE','结束之后，也交代清楚。','汇总本次电量、时长与费用，引导拔枪归位，再进入结算。'],payment:['CLEAR BILLING','每一笔费用，都有依据。','电费、服务费与优惠独立列明，实付金额突出，支付方式直接可选。'],paying:['PAYMENT IN PROGRESS','处理中，避免重复提交。','保留账单上下文，暂时禁用支付按钮，等待结果反馈。'],paid:['READY TO GO','让结束，成为轻松的下一程。','以明确的成功状态收尾，提供账单入口，并提醒检查充电枪。'],failed:['RECOVER WITH CONFIDENCE','出现问题，给出下一步。','用具体原因取代笼统报错，重试、换枪和客服都能就近找到。'],receipt:['ORDER DETAILS','完成之后，信息仍可追溯。','时间、电量、收费与支付结果集中保留，形成完整的充电记录。'],paymentfailed:['PAYMENT RECOVERY','付款中断，账单仍然保留。','说明本次未扣款，支持重新支付，让用户不必重复寻找订单。']};
const ring=()=>`<svg class="charge-ring" viewBox="0 0 180 110" aria-hidden="true"><path class="ring-track" d="M14 90 A76 76 0 0 1 166 90"/><path class="ring-progress" pathLength="100" d="M14 90 A76 76 0 0 1 166 90"/><circle class="ring-energy" r="3" cx="130" cy="25"/></svg>`;
const bolt='<svg class="charge-bolt" viewBox="0 0 24 24" aria-hidden="true"><path d="M13.5 2 4 13h7l-.5 9L20 11h-7l.5-9Z"/></svg>';
const car='<img class="charge-car" src="assets/ev-charge.webp" alt="正在补能的新能源汽车" width="1536" height="1024">';
class ChargeApp {
 constructor(el,opts={}){this.el=el;this.static=opts.static||false;this.state=el.dataset.initial||opts.state||'charging';this.target=80;this.gun='01';this.method='wechat';this.battery=68;this.energy=27.36;this.seconds=1398;this.agreed=true;this.timer=null;this.sessionTimer=null;this.toastTimer=null;this.visible=true;this.render();if(!this.static){el.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)this.act(b.dataset.action,b)});el.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const sheet=el.querySelector('.app-sheet');if(!sheet)return;const focusable=[...sheet.querySelectorAll('button:not(:disabled),input,a[href]')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}});el.addEventListener('change',e=>{if(e.target.name==='payment-'+this.el.dataset.app)this.method=e.target.value;if(e.target.dataset.agreement!==undefined){this.agreed=e.target.checked;const start=this.el.querySelector('[data-action="start"]');if(start)start.disabled=!this.agreed;}});this.sessionTimer=setInterval(()=>this.tick(),1500);this.observer=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting},{threshold:.05});this.observer.observe(el);}}
 money(){const electric=Math.round(this.energy*.65*100)/100,service=Math.round(this.energy*.283*100)/100,total=Math.round((electric+service)*100)/100,discount=Math.min(2,total);return{electric,service,total,discount,pay:Math.max(0,total-discount)};}
 time(){return `${String(Math.floor(this.seconds/60)).padStart(2,'0')}:${String(this.seconds%60).padStart(2,'0')}`}
 station(){return `<div class="app-station-line"><span class="plug-icon" aria-hidden="true">${bolt}</span><div><strong>充美三和广场超充站</strong><small>${this.gun} 号直流快充枪 · 250 kW</small></div><span class="tiny-tag">快充</span></div>`}
 row(l,r,c=''){return `<div class="app-detail-row ${c}"><span>${l}</span><b>${r}</b></div>`}
 button(label,action,cls='app-primary',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`}
 header(){return `<div class="app-status"><span>09:41</span><span class="status-icons"><span class="signal-bars" aria-label="信号"><i></i><i></i><i></i><i></i></span><span aria-hidden="true">⌁</span><i class="battery-icon" aria-label="电池"></i></span></div><div class="app-nav"><button class="app-back" data-action="back" aria-label="返回"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M12 4 6 10l6 6"/></svg></button><strong>${names[this.state]||'充电服务'}</strong><span class="mini-capsule" aria-label="小程序菜单"><svg class="mini-menu" viewBox="0 0 20 20" aria-hidden="true"><circle cx="4" cy="10" r="1.4"/><circle cx="10" cy="10" r="2.2"/><circle cx="16" cy="10" r="1.4"/></svg><i class="mini-divider"></i><svg class="mini-close" viewBox="0 0 20 20" aria-hidden="true"><circle cx="10" cy="10" r="6.3" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="10" cy="10" r="3.1"/></svg></span></div>`}
 chargeBody(){let m=this.money();return `<div class="charge-header"><span class="app-chip"><i></i> 连接稳定 · 正在快充</span><h3 class="app-headline">正在充电</h3></div><div class="charge-visual">${ring()}<div class="ring-number"><b data-live="battery">${Math.floor(this.battery)}</b><small>%</small></div>${car}<span class="charging-sheen" aria-hidden="true"></span></div><p class="app-estimate">预计 <strong data-live="remaining">12</strong> 分钟达到 ${this.target}%</p><div class="app-metrics"><div><b data-live="energy">${this.energy.toFixed(2)}</b><small>已充电量 / kWh</small></div><div><b data-live="time">${this.time()}</b><small>充电时长</small></div><div><b data-live="cost">${m.total.toFixed(2)}</b><small>累计费用 / 元</small></div></div><div class="app-card">${this.station()}<div class="app-separator"></div>${this.row('当前功率','72.8 kW')}${this.row('目标电量',`${this.target}% · 达到后自动停止`,'blue-row')}</div><p class="app-note">费用以结束后的实际结算为准。</p>`}
 readyBody(){return `<h3 class="app-headline">准备好了，即刻出发。</h3><p class="app-subline">请确认已插好充电枪，车辆处于驻车状态。</p><div class="ready-icon"><span class="plug-big" aria-hidden="true">${bolt}</span></div><div class="app-card">${this.station()}<div class="app-separator"></div>${this.row('当前电价','<span class="charge-price">0.9330 <small>元 / kWh</small></span>')}${this.row('电费 / 服务费','0.6500 / 0.2830 元')}</div><div class="app-card"><h4>充到多少，提前选好</h4><div class="app-goal">${[80,90,100].map(n=>`<button class="goal-pill ${this.target===n?'selected':''}" data-action="goal" data-value="${n}">${n}%</button>`).join('')}</div><p class="app-note">达到目标电量后自动停止充电。</p></div><label class="app-checkbox"><input type="checkbox" data-agreement ${this.agreed?'checked':''}><span>我已确认车辆和充电枪信息，并同意充电服务规则。</span></label>`}
 connectBody(stopping=false){return `<div class="app-center"><h3 class="app-headline">${stopping?'正在安全结束':'正在连接你的车辆'}</h3><p class="app-subline">${stopping?'请稍候，收到结束确认后再拔枪。':'正在检查连接状态，请暂时不要拔枪。'}</p></div><div class="connection-visual"><span aria-hidden="true">${bolt}</span></div><div class="app-card connect-steps"><div><i>✓</i> ${stopping?'结束请求已发送':'已识别充电枪'}</div><div><i>✓</i> ${stopping?'充电记录已保存':'车辆连接正常'}</div><div class="pending"><i></i> ${stopping?'等待设备结束确认':'正在进行安全校验'}</div></div><p class="app-note app-center">${stopping?'确认结束后将自动展示本次账单。':'请保持车辆处于驻车状态。'}</p>`}
 completeBody(){const m=this.money();return `<div class="app-center"><div class="result-symbol">✓</div><h3 class="result-title">本次充电已结束</h3><p class="result-caption">已停止供电，请拔枪归位。<br>准备好，再出发。</p></div><div class="app-metrics result-summary"><div><b>${Math.floor(this.battery)}<small style="display:inline">%</small></b><small>结束电量</small></div><div><b>${this.energy.toFixed(2)}</b><small>已充电量 / kWh</small></div><div><b>${this.time()}</b><small>充电时长</small></div></div><div class="app-card">${this.station()}<div class="app-separator"></div>${this.row('本次充电费用',`¥ ${m.total.toFixed(2)}`)}${this.row('可用优惠',`− ¥ ${m.discount.toFixed(2)}`,'blue-row')}${this.row('待支付',`<strong style="font-size:20px;color:#307af5">¥ ${m.pay.toFixed(2)}</strong>`)}</div><div class="paid-note"><span aria-hidden="true">♧</span><span>结束充电后请及时驶离车位，<br>给下一位车主留一份方便。</span></div>`}
 paymentBody(receipt=false){const m=this.money();return `<p class="app-receipt-head">${receipt?'已支付金额':'本次应付'}</p><div class="app-total"><small>¥</small>${m.pay.toFixed(2)}</div><div class="app-card"><h4>费用明细</h4>${this.row('充电电费',`¥ ${m.electric.toFixed(2)}`)}${this.row('充电服务费',`¥ ${m.service.toFixed(2)}`)}${this.row('充电优惠',`− ¥ ${m.discount.toFixed(2)}`,'blue-row')}<div class="app-separator"></div>${this.row('充电电量',`${this.energy.toFixed(2)} kWh`)}${this.row('充电时长',this.time())}</div>${receipt?`<div class="app-card">${this.station()}<div class="app-separator"></div>${this.row('支付状态','已支付','blue-row')}${this.row('支付方式',this.method==='wechat'?'微信支付':'账户余额')}${this.row('订单编号','CM202610070001')}</div>`:`<div class="app-card"><h4>选择支付方式</h4><label class="app-pay-option"><span class="pay-logo">微</span><span>微信支付</span><input type="radio" name="payment-${this.el.dataset.app}" value="wechat" ${this.method==='wechat'?'checked':''}></label><label class="app-pay-option"><span class="pay-logo wallet">¥</span><span>账户余额<small class="pay-option-sub">可用余额 ¥ 100.00</small></span><input type="radio" name="payment-${this.el.dataset.app}" value="wallet" ${this.method==='wallet'?'checked':''}></label></div>`}<p class="app-note app-center">${receipt?'本页面为设计演示账单。':'支付完成后，可在订单中心查看账单。'}</p>`}
 failedBody(pay=false){return `<div class="app-center"><div class="result-symbol warning">!</div><h3 class="result-title">${pay?'支付暂未完成':'暂时无法开始充电'}</h3><p class="result-caption">${pay?'网络连接中断，本次未扣款。<br>订单已保留，可以重新支付。':'设备连接超时，本次未产生费用。<br>请检查充电枪是否插紧后重试。'}</p></div><div class="app-card">${this.station()}<div class="app-separator"></div>${this.row(pay?'待付金额':'设备状态',pay?`¥ ${this.money().pay.toFixed(2)}`:'等待重新连接')}</div><div class="app-warning-box">${pay?'请确认网络正常后重试。你也可以在订单中心继续支付。':'① 检查充电枪是否插紧<br>② 确认车辆已处于驻车状态<br>③ 若仍无法启动，可更换空闲充电枪'}</div><div class="failure-actions">${this.button(pay?'查看订单':'更换充电枪',pay?'complete':'switch','app-secondary')}${this.button('联系客服','support','app-secondary')}</div>`}
 paidBody(){return `<div class="app-center"><div class="result-symbol">✓</div><h3 class="result-title">支付成功</h3><p class="result-caption">这一程，能量满满。</p><div class="app-total"><small>¥</small>${this.money().pay.toFixed(2)}</div><img class="ready-car" src="assets/ev-charge.webp" alt="新能源汽车" width="1536" height="1024"></div><div class="app-card">${this.row('支付方式',this.method==='wechat'?'微信支付':'账户余额')}${this.row('支付状态','已完成','blue-row')}</div><div class="paid-note"><span aria-hidden="true">✓</span><span>离开前，请确认充电枪已归位。<br>感谢你，让补能更美好。</span></div>`}
 modal(){return `<div class="app-modal-backdrop"><div class="app-sheet" role="dialog" aria-modal="true" aria-label="确认结束充电"><div class="sheet-handle"></div><h3>现在结束充电？</h3><p>当前电量 ${Math.floor(this.battery)}%，尚未达到 ${this.target}% 目标。<br>结束后将按实际充电量结算。</p><div class="sheet-stats"><span><b>${this.energy.toFixed(2)}</b>已充电量 / kWh</span><span><b>¥ ${this.money().total.toFixed(2)}</b>累计费用</span></div>${this.button('继续充电','continue')}${this.button('确认结束','stop','app-secondary')}</div></div>`}
 render(){clearTimeout(this.timer);this.el.dataset.state=this.state;let body='',bottom='';switch(this.state){case'ready':body=this.readyBody();bottom=this.button('确认并开始充电','start','app-primary',this.agreed?'':'disabled');break;case'connecting':body=this.connectBody();bottom=this.button('取消连接','cancel','app-secondary');break;case'charging':case'confirm':body=this.chargeBody();bottom=this.button('结束充电','confirm','app-danger');break;case'stopping':body=this.connectBody(true);bottom=this.button('正在等待设备确认…','none','app-secondary','disabled');break;case'complete':body=this.completeBody();bottom=this.button('去支付 · ¥ '+this.money().pay.toFixed(2),'payment');break;case'payment':case'paying':case'receipt':body=this.paymentBody(this.state==='receipt');bottom=this.state==='receipt'?this.button('返回充电主页','ready'):this.button(this.state==='paying'?'正在支付…':'确认支付 ¥ '+this.money().pay.toFixed(2),'pay','app-primary',this.state==='paying'?'disabled':'');break;case'paid':body=this.paidBody();bottom=this.button('查看本次账单','receipt');break;case'failed':case'paymentfailed':body=this.failedBody(this.state==='paymentfailed');bottom=this.button(this.state==='paymentfailed'?'重新支付':'重新连接',this.state==='paymentfailed'?'payment':'retry');break;}
 this.el.innerHTML=this.header()+`<div class="app-content">${body}</div><div class="app-bottom">${bottom}</div>`+(this.state==='confirm'?this.modal():'');this.updateNumbers();if(!this.static){if(this.state==='connecting')this.timer=setTimeout(()=>this.setState('charging'),2400);if(this.state==='stopping')this.timer=setTimeout(()=>this.setState('complete'),1800);if(this.state==='paying')this.timer=setTimeout(()=>this.setState('paid'),1700);}
 if(this.el.dataset.app==='lab'){document.querySelectorAll('[data-state]').forEach(b=>{if(b.tagName==='BUTTON'){const active=b.dataset.state===this.state;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));}});const c=copy[this.state]||copy.charging;document.getElementById('state-kicker').textContent=c[0];document.getElementById('state-title').textContent=c[1];document.getElementById('state-description').textContent=c[2];}
 }
 setState(state){this.state=state;this.render();}
 tick(){if(this.static||!this.visible||document.hidden||this.state!=='charging')return;if(this.el.dataset.app==='hero'){this.battery=68;this.updateNumbers();return;}this.seconds+=1;this.energy+=.0202;this.battery=Math.min(this.target,this.battery+.026);this.updateNumbers();if(this.battery>=this.target){if(this.el.dataset.app==='hero'){this.battery=68;this.energy=27.36;this.seconds=1398;this.updateNumbers()}else this.setState('stopping');}}
 updateNumbers(){const m=this.money(),values={battery:Math.floor(this.battery),energy:this.energy.toFixed(2),time:this.time(),cost:m.total.toFixed(2),remaining:Math.max(1,Math.ceil((this.target-this.battery)*.95))};this.el.querySelectorAll('[data-live]').forEach(e=>{e.textContent=values[e.dataset.live]});const p=this.el.querySelector('.ring-progress');if(p)p.style.strokeDashoffset=100-this.battery;const dot=this.el.querySelector('.ring-energy');if(dot){const angle=Math.PI*(1+this.battery/100);dot.setAttribute('cx',90+76*Math.cos(angle));dot.setAttribute('cy',90+76*Math.sin(angle));}}
 toast(text){this.el.querySelector('.app-toast')?.remove();const n=document.createElement('div');n.className='app-toast';n.role='status';n.textContent=text;this.el.append(n);clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>n.remove(),3000);}
 support(){const n=document.createElement('div');n.className='app-modal-backdrop';n.innerHTML=`<div class="app-sheet" role="dialog" aria-label="联系客服"><div class="sheet-handle"></div><h3>我们在这里帮你</h3><p>设备连接问题，请向客服提供站点与枪号。</p><div class="app-card">${this.station()}</div><p>可在小程序「客服中心」联系在线客服。<br>此处为交互设计演示。</p>${this.button('知道了','close-support')}</div>`;this.el.append(n);n.querySelector('button').focus();}
 act(action,b){if(this.static)return;switch(action){case'none':return;case'goal':this.target=+b.dataset.value;this.render();break;case'start':if(!this.agreed)return;this.energy=0;this.seconds=0;this.battery=42;this.setState('connecting');break;case'retry':this.energy=0;this.seconds=0;this.battery=42;this.setState('connecting');break;case'cancel':this.setState('ready');break;case'confirm':this.setState('confirm');this.el.querySelector('[data-action="continue"]').focus();break;case'continue':this.setState('charging');break;case'stop':this.setState('stopping');break;case'pay':this.setState('paying');break;case'switch':this.gun=this.gun==='01'?'02':'01';this.setState('ready');this.toast(`已切换至 ${this.gun} 号空闲充电枪`);break;case'support':this.support();break;case'close-support':this.el.querySelector('.app-modal-backdrop')?.remove();break;case'back':if(this.state==='confirm'){this.setState('charging')}else if(['charging','stopping','connecting'].includes(this.state)){this.toast('当前充电状态已保留')}else{this.setState('ready')}break;default:this.setState(action);}}
 destroy(){clearTimeout(this.timer);clearInterval(this.sessionTimer);clearTimeout(this.toastTimer);this.observer?.disconnect();}
}
window.chargingApps={};document.querySelectorAll('[data-app]').forEach(el=>window.chargingApps[el.dataset.app]=new ChargeApp(el));document.querySelectorAll('[data-static]').forEach((holder,i)=>{const app=document.createElement('div');app.className='app-screen';app.dataset.app='static-'+i;holder.append(app);new ChargeApp(app,{static:true,state:holder.dataset.static});const resize=()=>{const scale=(holder.clientWidth-8)/320;app.style.left='4px';app.style.top='4px';app.style.transform=`scale(${scale})`;holder.style.height=(710*scale+8)+'px';holder.style.aspectRatio='auto'};new ResizeObserver(resize).observe(holder);resize();});
let autoTimer=null,auto=true,autoIndex=0;const sequence=['ready','connecting','charging','confirm','stopping','complete','payment','paying','paid','failed'];const autoButton=document.getElementById('auto-play');
function setAutoLabel(){autoButton.innerHTML=auto?'<span>Ⅱ</span> 暂停自动演示':'<span>▶</span> 继续自动演示';autoButton.setAttribute('aria-pressed',String(auto))}
function advance(){if(!auto)return;if(autoIndex>=sequence.length)autoIndex=0;const a=window.chargingApps.lab;if(autoIndex===0){a.energy=27.36;a.seconds=1398;a.battery=68;a.target=80;a.gun='01'}const state=sequence[autoIndex++];a.setState(state);autoTimer=setTimeout(advance,state==='charging'?7000:3400)}
function holdForInteraction(){clearTimeout(autoTimer);if(auto)autoTimer=setTimeout(advance,12000)}
document.querySelectorAll('.flow-steps [data-state]').forEach(b=>b.addEventListener('click',()=>{holdForInteraction();window.chargingApps.lab.setState(b.dataset.state)}));autoButton.addEventListener('click',()=>{auto=!auto;clearTimeout(autoTimer);setAutoLabel();if(auto)advance()});window.chargingApps.lab.el.addEventListener('click',e=>{if(e.target.closest('[data-action]'))holdForInteraction()});setAutoLabel();advance();
document.addEventListener('keydown',e=>{if(e.key==='Escape'){Object.values(window.chargingApps).forEach(a=>{if(a.state==='confirm')a.setState('charging');else a.el.querySelector('.app-modal-backdrop')?.remove()})}});
const heroFrame=document.querySelector('.hero-device');
if(heroFrame){const fitHero=()=>heroFrame.style.setProperty('--hero-scale',(heroFrame.clientWidth-14)/320);new ResizeObserver(fitHero).observe(heroFrame);fitHero();}
})();
