(async()=>{
'use strict';
let screens=[];try{const res=await fetch('assets/screens.json?v=20261008-7',{cache:'no-store'});if(!res.ok)throw Error('load');screens=(await res.json()).filter(s=>!['24','32','36','38','42','50','54','64','72','73','74','75','76','77'].includes(s.id))}catch{document.getElementById('atlas-grid').textContent='界面暂未加载，请刷新页面重试。';return}
const grid=document.getElementById('atlas-grid'),filters=document.getElementById('category-filters'),dialog=document.getElementById('lightbox'),img=document.getElementById('lightbox-image');let visible=screens,index=0,returnFocus=null;
const groups=[['all','全部'],['01','登录与找站'],['02','充电站详情'],['04','地图找站'],['03','会员与活动'],['05','我的与钱包'],['06','车辆与电池'],['07','客服与反馈'],['08','信息与设置']];
for(const [id,name] of groups.filter(([id])=>id==='all'||screens.some(s=>s.group===id))){const b=document.createElement('button');b.type='button';b.textContent=name;b.dataset.group=id;b.className=id==='all'?'active':'';b.setAttribute('aria-pressed',String(id==='all'));b.addEventListener('click',()=>{filters.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});visible=id==='all'?screens:screens.filter(s=>s.group===id);grid.querySelectorAll('.atlas-card').forEach(c=>c.hidden=id!=='all'&&c.dataset.group!==id);document.getElementById('visible-count').textContent=visible.length+' 张界面';});filters.append(b)}
for(const s of screens){const f=document.createElement('figure');f.className='atlas-card';f.dataset.group=s.group;const b=document.createElement('button');b.className='image-open';b.dataset.screen=s.id;b.setAttribute('aria-label','放大查看：'+s.name);const im=new Image();im.src=s.src;im.alt=s.name;im.width=s.width;im.height=s.height;im.loading='lazy';im.decoding='async';b.append(im);const cap=document.createElement('figcaption');const text=document.createElement('div');text.textContent=s.name;const num=document.createElement('span');num.textContent=s.id+' ↗';cap.append(text,num);f.append(b,cap);grid.append(f)}
document.getElementById('total-count').textContent=screens.length;document.getElementById('visible-count').textContent=screens.length+' 张界面';
function show(i){index=(i+screens.length)%screens.length;const s=screens[index];document.getElementById('lightbox-title').textContent=s.name;document.getElementById('lightbox-position').textContent=`${index+1} / ${screens.length}`;img.src=s.full;img.alt=s.name;document.querySelector('.lightbox-body').scrollTop=0;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(!b)return;const i=screens.findIndex(s=>s.id===b.dataset.screen);if(i<0)return;returnFocus=b;show(i);dialog.showModal();document.body.style.overflow='hidden'});
const close=()=>dialog.close();document.getElementById('close-lightbox').addEventListener('click',close);dialog.addEventListener('close',()=>{document.body.style.overflow='';returnFocus?.focus({preventScroll:true})});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});document.getElementById('prev-image').addEventListener('click',()=>show(index-1));document.getElementById('next-image').addEventListener('click',()=>show(index+1));document.addEventListener('keydown',e=>{if(!dialog.open)return;if(e.key==='ArrowRight'){show(index+1);e.preventDefault()}if(e.key==='ArrowLeft'){show(index-1);e.preventDefault()}});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.system-board,.feature-phones,.daily-layout,.finale h2').forEach(e=>{e.classList.add('reveal');io.observe(e)})}
})();
