(()=>{'use strict';document.documentElement.classList.add('js');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(e=>reveal.observe(e));
const progress=()=>$('.reading-progress').style.transform=`scaleX(${scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`;addEventListener('scroll',progress,{passive:true});progress();
const navObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));}}),{rootMargin:'-15% 0px -65% 0px'});$$('main section[id]').forEach(e=>navObserver.observe(e));
function tabs(selector,callback){const buttons=$$(selector);buttons.forEach((b,i)=>{b.addEventListener('click',()=>{buttons.forEach(x=>{x.setAttribute('aria-selected',String(x===b));x.tabIndex=x===b?0:-1});callback(b,i)});b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight'||e.key==='ArrowDown')n=(i+1)%buttons.length;if(e.key==='ArrowLeft'||e.key==='ArrowUp')n=(i-1+buttons.length)%buttons.length;if(e.key==='Home')n=0;if(e.key==='End')n=buttons.length-1;if(n!==undefined){e.preventDefault();buttons[n].click();buttons[n].focus()}})})}
const roles=[['查找设备，完成产线布局。','选择设备、调整位置与连接关系，完成产线布局。','设备不好找，布局需要反复调整，影响搭建效率。'],['设置参数，模拟运行。','设置加工时间与物料路线，模拟运行，查找等待或堵塞环节。','设置分散，设备连接不清楚，异常难以及时发现。'],['比较方案，辅助决策。','对比方案的产量、设备效率与成本，选择合适的布局。','方案缺少统一对比，低效环节不容易找到。']];
tabs('[data-role]',(b,i)=>{$('#role-title').textContent=roles[i][0];$('#role-work').textContent=roles[i][1];$('#role-pain').textContent=roles[i][2];$('#role-panel').setAttribute('aria-labelledby',b.id)});
const zones=[['MODEL LIBRARY','快速找到所需设备。','按分类或搜索查找设备，浅蓝色标明当前选择；列表管理已放入场景的设备。','library',[2.8,8,12,31]],['LAYOUT & ANALYSIS','常用工具集中排列。','撤回、缩放、对齐与组合集中展示，编辑和分析工具分开排列。','layout-tools',[15,3.7,68,6]],['SPATIAL CANVAS','完整查看设备布局。','中间查看设备位置、区域边界与连接关系，可直接调整布局。','canvas',[13.3,10.5,74,85.4]],['OBJECT PROPERTIES','设置分组，便于核对。','右侧按设备信息、位置与运行方式分组，方便逐项设置。','properties',[87.5,5.5,12,53]],['PLAYBACK CONTROL','运行控制始终可见。','底部控制播放、停止与逐步运行，同时显示时间与进度。','playback',[12.7,95,74.8,4.8]]];
tabs('[data-zone]',(b,i)=>{const z=zones[i];$('#zone-kicker').textContent=z[0];$('#zone-title').textContent=z[1];$('#zone-desc').textContent=z[2];const box=$('.focus-zone');['left','top','width','height'].forEach((k,n)=>box.style[k]=z[4][n]+'%');$('#zone-panel').setAttribute('aria-labelledby',b.id)});
const stages=[['scene','01 / 空间与资源','搭建区域清晰可见。','左侧管理设备，中间查看布局，顶部提供编辑工具。',['可选设备与已用设备分开管理','完整展示产线布局','蓝色标明当前阶段']],['integration-stage','02 / 设备与系统','用连线展示设备关系。','用连线展示设备与系统的连接，选中后在右侧修改设置。',['连接模块管理设备','系统关联班组与订单','设备信息与连接设置分组展示']],['process-stage','03 / 工序与逻辑','按步骤设置生产流程。','按上料、切割、分拣等步骤连接设备，再设置执行条件。',['生产步骤清楚可见','每一步都有对应的执行条件','选中步骤后查看相关设置']]];
tabs('[data-stage]',(b,i)=>{const d=stages[i];$('#stage-image').src=`assets/screens/${d[0]}.webp`;$('#stage-image').alt=d[2];$('#stage-open').dataset.image=d[0];$('#stage-open').setAttribute('aria-label','放大查看'+d[2]);$('#stage-number').textContent=d[1];$('#stage-title').textContent=d[2];$('#stage-desc').textContent=d[3];$('#stage-points').replaceChildren(...d[4].map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('#stage-panel').setAttribute('aria-labelledby',b.id)});
let screens=[],shown=[],modalItems=[],current=0,trigger;
const dialog=$('#image-dialog');function showImage(id){current=modalItems.findIndex(x=>x.id===id);if(current<0)return;const item=modalItems[current];$('#dialog-img').src=item.full||`assets/screens/${item.id}.webp`;$('#dialog-img').alt=item.title;$('#dialog-title').textContent=item.title;$('#dialog-index').textContent=`${String(current+1).padStart(2,'0')} / ${modalItems.length}`}
function renderGallery(filter='all'){shown=screens.filter(x=>filter==='all'||x.cat===filter);$('#gallery-count').textContent=`${shown.length} 个界面`;$('#gallery-grid').innerHTML=shown.map((x,i)=>`<figure class="gallery-card"><button class="image-open" data-image="${x.id}" aria-label="放大查看${x.title}"><img src="assets/thumbs/${x.id}.webp" width="${x.width}" height="${x.height}" alt="${x.title}" loading="lazy"><span class="zoom">↗</span></button><figcaption>${x.title}<span>${String(i+1).padStart(2,'0')}</span></figcaption></figure>`).join('')}
fetch('screens.json').then(r=>{if(!r.ok)throw Error('Gallery unavailable');return r.json()}).then(data=>{screens=data;renderGallery()}).catch(()=>{$('#gallery-count').textContent='界面暂未加载，请刷新重试。'});
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderGallery(b.dataset.filter)}));
document.addEventListener('click',e=>{const b=e.target.closest('[data-image]');if(!b||!screens.length)return;trigger=b;modalItems=b.closest('.gallery-card')?shown:screens;showImage(b.dataset.image);dialog.showModal();document.body.classList.add('modal-open')});
$('#dialog-close').addEventListener('click',()=>dialog.close());$('#prev-image').addEventListener('click',()=>showImage(modalItems[(current-1+modalItems.length)%modalItems.length].id));$('#next-image').addEventListener('click',()=>showImage(modalItems[(current+1)%modalItems.length].id));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')$('#prev-image').click();if(e.key==='ArrowRight')$('#next-image').click()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');trigger?.focus({preventScroll:true})});
const hero=$('.hero'),pauseMotion=()=>{const r=hero.getBoundingClientRect();hero.dataset.motion=document.hidden||r.bottom<0||r.top>innerHeight?'paused':'running'};new IntersectionObserver(pauseMotion).observe(hero);document.addEventListener('visibilitychange',pauseMotion);
})();
